allowBuilds:
  unrs-resolver: true
minimumReleaseAgeExclude:
  - eslint-plugin-perfectionist@5.9.1
  - '@aarsteinmedia/lottie-web@1.4.3'
onlyBuiltDependencies:
  - '@swc/core'
  - esbuild
  - unrs-resolver
